(def synth (daw/plugin "plugins/synth_mono/build/plugin.perone" {:vcf_cutoff 500}))
(def filter (daw/plugin "plugins/tibia_test/build/plugin.perone" {:cutoff 2000}))
(def cutoff ((daw/info synth) 26))
(assert (= [(cutoff :name) (cutoff :unit) (cutoff :min) (cutoff :max) (cutoff :default) (cutoff :integer)]
           [:vcf_cutoff "hz" 20 20000 20000 false]))
(assert (= (length (daw/info synth)) 39))
(assert (= (((daw/info synth) 38) :direction) :output))
(assert (= (((daw/info synth) 38) :name) :level))
(assert (= (cutoff :map) :logarithmic))
(assert (= (get-in (daw/product synth) [:parameters 26 :id]) "vcf_cutoff"))
(assert (= ((daw/product synth) :bundleName) "bw_example_synth_mono"))
(assert (find |($ :scale-points) (daw/info synth)))
(daw/track synth {:effects [filter]})
(daw/note synth 0 1 60)
(daw/param synth 0.25 :vcf_cutoff 4000)
(daw/param filter 0.5 :cutoff 500)
(daw/end 1.5)
