(import ./trace-helper :as external)
(import ../lib/pattern :as p)
(def synth (daw/plugin "build/fixture.perone" {:gain 0.001}))
(def fx (daw/plugin "build/effect.perone"))
(daw/track synth {:effects [fx]})
(daw/master)
(def items @[])
(external/fill items synth)
(daw/schedule 0 60 (p/events 0.4 items))
(for i 0 1200
  (daw/note synth (* i 0.005) 0.03 (+ 60 (% i 12)) 80))
(daw/note synth 0 6.5 48 90)
(daw/param synth 0.2 :gain 0.002)
(daw/end 7)
