(defn rejects [f]
  (assert (try (do (f) false) ([_] true)) "expected an API error"))
(def plugin "examples/synth_mono/plugin.so")
(def synth (daw/instrument plugin {:params [0 65]}))
(def effect (daw/instrument "examples/tibia_test/plugin.so"))
(def spare (daw/instrument plugin))
(def nan (/ 0 0))
(each f [
  (fn [] (daw/instrument))
  (fn [] (daw/instrument "build/nonexistent.so"))
  (fn [] (daw/instrument plugin {:pan 2}))
  (fn [] (daw/instrument plugin {:gain nan}))
  (fn [] (daw/instrument plugin {:send -1}))
  (fn [] (daw/instrument plugin {:color :unknown}))
  (fn [] (daw/instrument plugin {:params [0]}))
  (fn [] (daw/instrument plugin {:params [0 nan]}))
  (fn [] (daw/instrument plugin {:params [-1 1]}))
  (fn [] (daw/note synth))
  (fn [] (daw/note -1 0 0.1 60))
  (fn [] (daw/note 3 0 0.1 60))
  (fn [] (daw/note synth -1 0.1 60))
  (fn [] (daw/note synth nan 0.1 60))
  (fn [] (daw/note synth 600 0.1 60))
  (fn [] (daw/note synth 0 0 60))
  (fn [] (daw/note synth 0 0.000001 60))
  (fn [] (daw/note synth 0 0.1 128))
  (fn [] (daw/note synth 0 0.1 60.5))
  (fn [] (daw/note synth 0 0.1 60 0))
  (fn [] (daw/param synth 0 -1 2))
  (fn [] (daw/param synth 0 0 (/ 1 0)))
  (fn [] (daw/drum :unknown 0 1))
  (fn [] (daw/drum :kick -1 1))
  (fn [] (daw/drum :kick 0 2))
  (fn [] (daw/export nan))
  (fn [] (daw/export 0))
  (fn [] (daw/export 601))] (rejects f))

# Deliberately unsorted; controls retain insertion order, off precedes on.
(daw/note synth 0.5 0.5 64)
(daw/param synth 0.5 0 30)
(daw/param synth 0.5 0 70)
(daw/note synth 0 0.5 60)
(gccollect)
(rejects (fn [] (daw/export 0.9)))
(for i 0 2047 (daw/param spare 0 0 40))
(rejects (fn [] (daw/note spare 0 0.1 60))) # Two slots or no mutation.
(daw/param spare 0 0 41)
(rejects (fn [] (daw/param spare 0 0 42)))
(for i 3 16 (daw/instrument plugin))
(rejects (fn [] (daw/instrument plugin)))
(for i 0 8192 (daw/drum :hat 0 0.1))
(rejects (fn [] (daw/drum :hat 0 0.1)))
(daw/export 1)
(each f [(fn [] (daw/export 1)) (fn [] (daw/instrument plugin))
         (fn [] (daw/note synth 0 0.1 60)) (fn [] (daw/param synth 0 0 40))
         (fn [] (daw/drum :kick 0 1))] (rejects f))
