BRICKWORKS ?= ../../../brickworks
PLUGIN_DIR = $(BRICKWORKS)/examples/synth_mono/src
override CPPFLAGS += -I$(abspath $(BRICKWORKS)/include) -I$(abspath $(BRICKWORKS)/examples/common/src)
include ../plugin.mk
